from pydantic import BaseModel, Field, ConfigDict
from typing import Optional

# Schema for creating a new book
class BookCreate(BaseModel):
    # Title of the book (required)
    title: str

    # Author of the book (required)
    author: str

    # Year of publication (optional)
    # - Default: None (can be omitted)
    # - Must be greater than or equal to 1 if provided
    # - Description will appear in Swagger/OpenAPI docs
    year: Optional[int] = Field(
        default=None,
        ge=1,
        description="Year must be greater than 0"
    )


# Schema for reading book data (includes ID)
class BookRead(BookCreate):
    # Unique identifier for the book (auto-generated by the database)
    id: int

    # Configuration for Pydantic v2
    # Allows model creation directly from ORM objects (e.g., SQLAlchemy)
    model_config = ConfigDict(from_attributes=True)
